### ISSUE TITLE
Dynamically Load Introspection Schema

### ISSUE THREAD

**Issue by maxschridde1494** [maxschridde1494/ra-data-graphql-supabase#1]
Introspection schema should be dynamically pulled from the GQL API. `ra-data-graphql` dynamic introspectionResult generation is erroring out silently, resulting in an introspectionResult with an empty resources array and data provider errors such as below:

`
Error: Unknown resource players. Make sure it has been declared on your server side schema. Known resources are 
    at buildQuery2 (buildQuery.ts:24:23)
    at index.ts:183:15
    at step (introspection.ts:154:5)
    at Object.next (introspection.ts:154:5)
    at fulfilled (introspection.ts:154:5)
`

Digging into the introspectionResult generation in `ra-data-graphql`, the introspection query response includes verbose types:

```
{
    "kind": "SCALAR",
    "name": "BigFloat",
    "fields": null,
    "__typename": "BigFloat",
    "enumValues": [],
    "interfaces": [],
    "description": "A high precision floating point value represented as a string",
    "inputFields": null,
    "possibleTypes": null
}
```

However, the apollo client seems to be transforming this and my returned schema from the apollo client has a trimmed version of this type object that only includes __typename 

```
{
    __typename: 'BigFloat'
}
```

Current workaround is to pass the API's introspection schema directly into the dataProvider. i.e.

```
import buildGraphQLProvider, { defaultIntrospection } from 'ra-data-graphql-supabase'

import { apolloClient } from '../../clients/apolloClient' 
import introspectionSchema from './introspection-schema.json'

const introspection= {
    ...defaultIntrospection,
    schema: introspectionSchema["__schema"]
}

export async function initDataProvider(options?: any) {
    return buildGraphQLProvider({
        bulkActionsEnabled: true,
        client: apolloClient,
        introspection,
        ...options,
    })
}
```

**Comment by maxschridde1494** [comment]
This appears to be a `ra-data-graphql` issue. The `fetchSchema` method sets a fetch policy of `network-only`. Looking at the apollo docs, this shouldn't do any caching (afaict), but I am seeing different results in practice. 

My current workaround is to fetch the schema myself using a fetch policy of `no-cache` and pass that into the dataprovider init.

```
import buildGraphQLProvider, { defaultIntrospection } from 'ra-data-graphql-supabase'
import { IntrospectionOptions } from 'ra-data-graphql'
import { getIntrospectionQuery, IntrospectionQuery, IntrospectionSchema } from 'graphql';

import { apolloClient } from '../../clients/apolloClient' 
import { gql } from '@apollo/client';

const introspection: IntrospectionOptions = {
    ...defaultIntrospection
}

const fetchSchema = (): Promise<IntrospectionSchema> =>
    apolloClient
        .query<IntrospectionQuery>({
            fetchPolicy: 'no-cache',
            query: gql`
                ${getIntrospectionQuery()}
            `,
        })
        .then(({ data: { __schema } }) => __schema);

export async function initDataProvider(options?: any) {
    introspection.schema = await fetchSchema()

    return buildGraphQLProvider({
        bulkActionsEnabled: true,
        client: apolloClient,
        introspection,
        ...options,
    })
}
```
